import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideBarNavigation from './components/SideBarNavigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=""> {children}</main>
        <footer>{/* Footer content */}</footer>
      </body>
    </html>
  )
}
